{
  "type": "record",
  "name": "CustomerEventValue",
  "namespace": "com.thai.learning",
  "fields": [
    {
      "name": "header",
      "type": {
        "type": "record",
        "name": "EventHeader",
        "fields": [
          {
            "name": "event_id",
            "type": "string"
          },
          {
            "name": "event_type",
            "type": "string"
          },
          {
            "name": "event_time",
            "type": "string"
          },
          {
            "name": "source_system",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "CustomerPayload",
        "fields": [
          {
            "name": "customer_id",
            "type": "string"
          },
          {
            "name": "order_id",
            "type": "string"
          },
          {
            "name": "amount",
            "type": "double"
          },
          {
            "name": "currency",
            "type": "string"
          },
          {
            "name": "country",
            "type": "string"
          }
        ]
      }
    }
  ]
}